if: (type = push AND branch = master) OR (type = pull_request)

sudo: required
dist: bionic
language: node_js
node_js:
  - node

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full pandoc latexmk pdf2svg
  - sudo apt-get install python3 python3-pip python3-setuptools
  - pip3 install --upgrade pip
  - pip3 install beautifulsoup4
  - npm -g install mathjax-node-page

before_script:
  - chmod +x ./travis/_make4ht.sh
  - chmod +x ./travis/_deploy.sh

script:
  - ./travis/_make4ht.sh
  - echo make4ht --version
  - make clean
  - make all
  - cd output/html && cd ../../
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_EVENT_TYPE" = "push" ]; then ./travis/_deploy.sh; fi