name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean Workspace
      uses: AutoModality/action-clean@v1.1.0

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16.20'
    
    - name: Build project
      run: make

    - name: Publish the web pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output/html
        enable_jekyll: false
      if: github.ref_name == 'master' && github.event_name == 'push'

     #- name: Deploy project to website
     # run: ./scripts/_deploy.sh
     # env:
     #   GITHUB_ACTOR: ${{ github.actor}}
     #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #   GITHUB_REPOSITORY: ${{ github.repository }}
     # if: github.ref_name == 'master' && github.event_name == 'push'

